import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from './Components/Navber/Navber.jsx'
import Footer from './Components/Footer/Footer.jsx'
import { CartProvider } from './context/CartContext.jsx'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <Navber/>
          {children}
          <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
